### PR TITLE
Patch a

### PR DESCRIPTION
**Pull request by jmhauck**

### CODE REVIEW

**Review by MikeTschudi — APPROVED** [review]

**Review by MikeTschudi — COMMENTED** [review]
My comment was lost; to repeat:
If `this._table.state === 'loaded'` is sometimes not hit, does that mean that the `await this.reactiveUtils.once()` call stalls the app?  Since the setTimeout is always called to check for this problem after a second, should it be moved before `await this.reactiveUtils.once()`?

**Comment by jmhauck** [comment]
@MikeTschudi good call...I can't actually say at this point if it stalls there...but makes sense that it could. We can certainly still continue working with the app but the functions its supposed to call on table load don't occur. I'll go ahead and move it before just in case.

**Comment by jmhauck** [comment]
@MikeTschudi seems like its failing on `npm run build` in codeql-analysis.yml. I see some suggesting something like `CI=false npm run build` any ideas on how we should address?

**Comment by MikeTschudi** [comment]
The build errors have been really strange.  I restarted the PR's Travis a couple of times without luck.  I'm trying the other PRs after boosting Travis to use Node 18 (for Stencil and Puppeteer) and a later Ubuntu (for Node 18).  Got them all to pass; now merged in this PR to see if that works.

**Comment by MikeTschudi** [comment]
Looks good; let's merge this via PR #708

**Comment by jmhauck** [comment]
Thanks @MikeTschudi

**Comment by jmhauck** [comment]
#645

**Pull request merged**
