### PR TITLE
update calcite

### PR DESCRIPTION
**Pull request by jmhauck**
Not having `esri/calcite-design-tokens` caused a build warning in components but then caused a build failure in the IA.

### CODE REVIEW

**Review by MikeTschudi — APPROVED** [review]
Just checking:  in layer-table and map-layer-picker, it's intentional to wrap each dropdown item in its own dropdown group?

**Comment by jmhauck** [comment]
Yes. The reason I put them items in groups was because I couldn't set as disabled on dropdown items after the calcite update.

**Comment by MikeTschudi** [comment]
How maddening!

**Comment by jmhauck** [comment]
Yes indeed

**Pull request merged**
